import React from 'react';
import './global.css';
import { ToastContainer } from 'react-toastify';
import ReactQueryProvider from '../shared/Providers/ReactQueryProvider';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          {children}
          <ToastContainer />
        </body>
      </html>
    </ReactQueryProvider>
  );
}
